name: swift_ride
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.7.0
  geolocator: ^13.0.4 # Updated to resolve conflict
  flutter_polyline_points: ^3.0.1
  flutter_dotenv: ^5.1.0
  permission_handler: ^11.3.1
  fluttertoast: ^8.2.8
  qr_flutter: ^4.1.0
  # Additional dependencies for other features
  get: ^4.6.6
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.3
  pinput: ^5.0.0
  flutter_faq: ^1.0.1+1
  font_awesome_flutter: ^10.7.0
  flutter_rating_bar: ^4.0.1
  d_chart: ^2.6.9
  fl_chart: ^0.68.0
  dotted_border: ^2.1.0
  percent_indicator: ^4.2.3
  loading_animation_widget: ^1.2.1
  image_picker: ^1.1.2
  zoom_pinch_overlay: ^1.4.3
  shared_preferences: ^2.3.0
  get_storage: ^2.1.1
  flutter_svg: ^2.0.10+1
  device_preview: ^1.2.0
  flutter_spinkit: ^5.2.1
  flutter_html: ^3.0.0
  geocoding: ^3.0.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  page_transition: ^2.1.0
  intl_phone_field: ^3.2.0
  url_launcher: ^6.3.1
  location: ^7.0.0
  flutter_map_location_marker: ^9.0.0
  envied: ^0.5.4+1
  web_socket_channel: ^3.0.1
  connectivity_plus: ^6.0.5
  socket_io_client: ^3.0.0
  open_settings_plus: ^0.4.0
  flutter_google_maps_webservices: ^1.1.1
  signature: ^5.5.0
  video_player: ^2.9.1
  dot_navigation_bar: ^1.0.2
  sweet_nav_bar: ^1.0.7
  smooth_page_indicator: ^1.2.1
  animated_notch_bottom_bar: ^1.0.3
  table_calendar: ^3.1.2
  custom_text_field_with_drop_down: ^0.0.12
  flutter_staggered_grid_view: ^0.7.0
  share_plus: ^10.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - .env
  fonts:
    - family: sf-pro-display
      fonts:
        - asset: assets/fonts/sf-pro-display/SFPRODISPLAYBLACKITALIC.OTF
          weight: 900
          style: italic
        - asset: assets/fonts/sf-pro-display/SFPRODISPLAYBOLD.OTF
          weight: 700
        - asset: assets/fonts/sf-pro-display/SFPRODISPLAYHEAVYITALIC.OTF
          weight: 800
          style: italic
        - asset: assets/fonts/sf-pro-display/SFPRODISPLAYLIGHTITALIC.OTF
          weight: 300
          style: italic
        - asset: assets/fonts/sf-pro-display/SFPRODISPLAYMEDIUM.OTF
          weight: 500
        - asset: assets/fonts/sf-pro-display/SFPRODISPLAYREGULAR.OTF
          weight: 400
        - asset: assets/fonts/sf-pro-display/SFPRODISPLAYSEMIBOLDITALIC.OTF
          weight: 600
          style: italic
        - asset: assets/fonts/sf-pro-display/SFPRODISPLAYTHINITALIC.OTF
          weight: 200
          style: italic
        - asset: assets/fonts/sf-pro-display/SFPRODISPLAYULTRALIGHTITALIC.OTF
          weight: 100
          style: italic